### ISSUE TITLE
text2hash: Wrong algorithm used for SHA3-512

### ISSUE THREAD

**Issue by TheKrunch** [fastily/ftools#1]
I was linked to [text2hash](https://ftools.toolforge.org/text2hash.html) from [this](https://en.wikipedia.org/wiki/Template:Committed_identity#Obtaining_a_hash) Wikipedia page. I then wanted to make sure I could replicate the results and when I tried, I found that other hash tools resulted in a different hash.

I believe this is because [the function](https://github.com/fastily/ftools/blob/4db4de02892c534e111206c9ee7c6963054520ab/text2hash.html#L68) that is being called from CryptoJS is actually using the Keccak-512 algorithm. If you look at the [Google Code Archive](https://code.google.com/archive/p/crypto-js/) for CryptoJS, and scroll to the __NOTE__ they mention that the SHA3 function is misnamed.

If you use the input `hello world` as an example, when using text2hash in the sha3-512 mode, its result matches the output from the Keccak-512 hash algorithm.

[text2hash](https://ftools.toolforge.org/text2hash.html) (sha3-512):
`3ee2b40047b8060f68c67242175660f4174d0af5c01d47168ec20ed619b0b7c42181f40aa1046f39e2ef9efc6910782a998e0013d172458957957fac9405b67d`

[emn178's tool (sha3-512)](https://emn178.github.io/online-tools/sha3_512.html):
`840006653e9ac9e95117a15c915caab81662918e925de9e004f774ff82d7079a40d4d27b1b372657c61d46d470304c88c788b3a4527ad074d1dccbee5dbaa99a`

[emn178's tool (Keccak-512)](https://emn178.github.io/online-tools/keccak_512.html):
`3ee2b40047b8060f68c67242175660f4174d0af5c01d47168ec20ed619b0b7c42181f40aa1046f39e2ef9efc6910782a998e0013d172458957957fac9405b67d`

I also tested this locally with the program [HashTab](http://implbits.com/products/hashtab/) which verified my conclusion.

To fix this, I think you should relabel the dropdown option of "sha3-512 (strong)" to "Keccak-512 (strong)". People on Wikipedia have been using this tool to create their Confirmed Identity Hashes, and if someone checks the hash without using this specific tool, they will get the "wrong" result for sha3-512. I suggested adding a note to the website explaining this change.

**Comment by fastily** [comment]
Hi @TheKrunch:

Thanks for the heads up, I was unaware of the naming discrepancy in CryptoJS.  I'll update the label in text2hash to read Keccak-512.
